class TagType
  ARCHERY = "archery"
  BACKPACKING = "backpacking"
  CAMPING = "camping"
  BAKING = "baking"
  BOARDGAMES = "boardgames"
  BOOKS = "books"
  COMICS = "comics"
  COOKING = "cooking"
  DIY = "diy"
  EDC = "edc"
  FOOD = "food"
  FITNESS = "fitness"
  GEAR = "gear"
  GUIDES = "guides"
  HIKING = "hiking"
  HUNTING = "hunting"
  LEGO = "lego"
  KNIVES = "knives"
  MIXOLOGY = "mixology"
  MUSIC = "music"
  OUTDOORS = "outdoors"
  RUNNING = "running"
  SCIENCE = "science"
  TOOLS = "tools"
  TOYS = "toys"
end