app_title: "The Pursuit of Hobbiness"
app_title_components: ['Pursuit','Hobbiness']
app_description: 'Find a new hobby. All the guides and gear you need to pursue hobbies like art, cooking, beekeeping, archery, running, and more.'
app_keywords: ['pursuit', 'hobby', 'hobbies', 'gear', 'guide', 'ideas', 'how to', 'gifts']