app_title: "The Pursuit of Hobbiness"
app_url: "pursuitofhobbiness.com"
app_title_components: ['Pursuit','Hobbiness']
app_description: 'Guides and gear to help you pursue hobbies like archery, beekeeping, cooking, and more.  Find your passion.'
app_keywords: ['pursuit', 'hobby', 'hobbies', 'gear', 'guide', 'ideas', 'how to', 'gifts']