app_title: "The Pursuit of Hobbiness"
app_url: "pursuitofhobbiness.com"
app_title_components: ['Pursuit','Hobbiness']
app_description: 'Guides and gear for hobbies you love.  Pursue your passion.'
app_keywords: ['pursuit', 'hobby', 'hobbies', 'gear', 'guide', 'ideas', 'how to', 'gifts']